CREATE TABLE "donor_profile" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"full_name" varchar(255) NOT NULL,
	"phone" varchar(20),
	"donor_type" varchar(100),
	"organization" varchar(255),
	"id_document" varchar(100),
	"address" text,
	"city" varchar(100),
	"state" varchar(100),
	"postal_code" varchar(20),
	"country" varchar(100) DEFAULT 'México',
	"medical_license" varchar(100),
	"medical_license_verified" boolean DEFAULT false,
	"verification_status" varchar(50) DEFAULT 'pending' NOT NULL,
	"verification_document" varchar(500),
	"verified_at" timestamp,
	"total_donations" integer DEFAULT 0,
	"total_medications_donated" integer DEFAULT 0,
	"recent_donations" integer DEFAULT 0,
	"profile_picture" varchar(500),
	"bio" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "donor_profile_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "recipient_profile" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"full_name" varchar(255) NOT NULL,
	"phone" varchar(20),
	"date_of_birth" timestamp,
	"recipient_type" varchar(100),
	"id_document" varchar(100),
	"social_security_number" varchar(100),
	"address" text,
	"city" varchar(100),
	"state" varchar(100),
	"postal_code" varchar(20),
	"country" varchar(100) DEFAULT 'México',
	"employment_status" varchar(100),
	"monthly_income" varchar(100),
	"has_health_insurance" boolean DEFAULT false,
	"insurance_provider" varchar(255),
	"socioeconomic_score" integer,
	"chronic_conditions" text,
	"allergies" text,
	"current_medications" text,
	"disabilities" text,
	"verification_status" varchar(50) DEFAULT 'pending' NOT NULL,
	"verification_document" varchar(500),
	"economic_proof" varchar(500),
	"verified_at" timestamp,
	"total_requests" integer DEFAULT 0,
	"total_medications_received" integer DEFAULT 0,
	"total_received" integer DEFAULT 0,
	"profile_picture" varchar(500),
	"bio" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "recipient_profile_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "donor_profile" ADD CONSTRAINT "donor_profile_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recipient_profile" ADD CONSTRAINT "recipient_profile_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;