// src/server/db/seed-data.ts

export const mockMedications = [
  {
    activeSubstance: "Paracetamol",
    dosage: "500mg",
    quantity: 20,
    presentation: "Caja con 20 tabletas",
    brand: "Tempra",
    expiryDate: new Date("2026-08-15"),
    lotNumber: "LOT2024A123",
    laboratory: "Reckitt Benckiser",
    postalCode: "07738",
    preferredSchedule: "Lunes a Viernes 9:00-18:00",
    location: "Metro Politcnico, CDMX",
    description:
      "Medicamento nuevo, caja cerrada. Sobró de un tratamiento dental.",
    status: "disponible" as const,
    isControlled: false,
    photoUrl: "/paracetamol-pills-box.jpg",
    donorName: "María González",
    donorEmail: "maria@example.com",
    donorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
  },
  {
    activeSubstance: "Amoxicilina",
    dosage: "500mg",
    quantity: 14,
    brand: "Amoxil",
    presentation: "Caja con 14 cápsulas",
    expiryDate: new Date("2026-12-20"),
    lotNumber: "AMX-9982",
    laboratory: "GlaxoSmithKline",
    photoUrl: "/amoxicillin-antibiotics-capsules.jpg",
    location: "ESCOM IPN, CDMX",
    postalCode: "07738",
    preferredSchedule: "Sábados de 10:00 a 14:00",
    description: "Antibiótico sellado. Caducidad amplia.",
    status: "disponible" as const,
    isControlled: false,
    donorName: "Carlos Ramírez",
    donorEmail: "carlos@example.com",
    donorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
  },
  {
    activeSubstance: "Insulina Glargina",
    dosage: "100UI/ml",
    quantity: 2,
    brand: "Lantus",
    presentation: "Pluma precargada (Solostar)",
    expiryDate: new Date("2026-09-30"),
    lotNumber: "INS-2025-X",
    laboratory: "Sanofi",
    photoUrl: "/insulin-pen-diabetes-medication.jpg",
    location: "Puebla, Puebla",
    postalCode: "72000",
    preferredSchedule: "Cualquier día previa cita",
    description:
      "Mantenida en refrigeración constante. Mi familiar cambió de marca.",
    status: "disponible" as const,
    isControlled: true,
    donorName: "Dr. Luis Hernández",
    donorEmail: "luis@example.com",
    donorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Luis",
  },
];

export const extraUsers = [
  {
    name: "Juan Solicitante",
    email: "juan.beneficiario@example.com",
    role: "beneficiary",
    isDonor: false,
    isBeneficiary: true,
  },
  {
    name: "Dra. Elena Híbrida",
    email: "elena.dual@example.com",
    role: "mixed",
    isDonor: true,
    isBeneficiary: true,
  },
];
